# Generated by Django 5.2.1 on 2025-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
            ],
        ),
    ]
