# Generated by Django 5.2.1 on 2025-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='add_num',
            field=models.CharField(default='add001', max_length=20),
        ),
    ]
